name: dating_app
description: Flutter Dating App

publish_to: 'none'

version: 1.1.0+11

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons:

  # FIREBASE Packages Section
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  firebase_messaging: ^14.0.4
  firebase_storage: ^11.2.2
  google_mobile_ads: ^2.3.0

  in_app_purchase: ^3.1.7
  flutter_svg: ^1.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0
  country_code_picker: ^2.0.2
  scoped_model: ^2.0.0
  image_picker: ^0.8.7+5
  image_cropper: ^4.0.1
  url_launcher: ^6.1.11
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  timeago: ^3.7.0
  share: ^2.0.4
  flutter_cupertino_datetime_picker: ^3.0.0
  place_picker: ^0.10.0
  fluttertoast: ^8.2.2
  flutter_screenutil: ^5.9.0
  zego_uikit_prebuilt_call: ^4.14.3
  zego_uikit_signaling_plugin: ^2.5.2
  device_info_plus: ^9.1.0
  zego_express_engine: ^3.10.0
  razorpay_flutter: ^1.3.7

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/app_logo.png"
  android: true
  ios: true
